/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.15.1+p3-gf46d68bf
 *
 * Project: 'traffic.Release+AppKit-E7' 
 * Target:  'Release+AppKit-E7' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.26.5 */
#define RTE_ETHOS_U_CORE_DRIVER
/* ARM::SDS:IO:USB&MDK USB@3.0.0 */
#define RTE_SDS_IO                              /* SDSIO */
#define RTE_SDS_IO_CLIENT                       /* SDSIO-Client */
#define RTE_SDS_IO_CLIENT_USB                   /* SDSIO-Client via USB */
#define RTE_SDS_IO_CLIENT_USB_MDK               /* SDSIO-Client via USB - MDK-Middleware USB */
/* ARM::SDS:Stream&CMSIS-RTOS2@3.1.0 */
#define RTE_SDS                                 /* Synchronous Data Stream (SDS) */
/* AlifSemiconductor::BSP:External peripherals:CAMERA Sensor MT9M114@2.2.0 */
#define RTE_Drivers_CAMERA_SENSOR_MT9M114            /* Driver CAMERA Sensor */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@2.2.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL    /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::CMSIS Driver:GPIO@1.0.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::CMSIS Driver:I2C@2.2.0 */
#define RTE_Drivers_I2C              /* Driver I2C */
/* AlifSemiconductor::CMSIS Driver:USART@2.2.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::CMSIS Driver:USB Device@2.2.0 */
#define RTE_Drivers_USBD          /* Driver USBD  */
/* AlifSemiconductor::Device:SOC Peripherals:CDC@2.2.0 */
#define RTE_Drivers_CDC200                 /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:CPI@2.2.0 */
#define RTE_Drivers_CPI              /* Driver CAMERA Controller */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.2.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@2.2.0 */
#define RTE_Drivers_MIPI_CSI2              /* Driver MIPI CSI2 */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@2.2.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@2.2.0 */
#define RTE_Drivers_MIPI_DSI               /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.2.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* Keil::USB&MDK:CORE@8.0.2 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Device:Custom Class@8.0.2 */
#define RTE_USB_Device_CustomClass_0    /* USB Device Custom Class instance 0 */

/* Keil::USB&MDK:Device@8.0.2 */
#define RTE_USB_Device_0                /* USB Device 0 */

/* PyTorch::Machine Learning:ExecuTorch:Backend EthosU@1.5.1 */
#define RTE_ML_EXECUTORCH_BACKEND_ETHOS_U     /* ExecuTorch Ethos-U Backend (Cortex-M host) */
/* PyTorch::Machine Learning:ExecuTorch:Kernel Registration@1.5.1 */
#define RTE_ML_EXECUTORCH_KERNEL_REGISTRATION     /* ExecuTorch Kernel Registration */
/* PyTorch::Machine Learning:ExecuTorch:Kernel Utils@1.5.1 */
#define RTE_ML_EXECUTORCH_KERNEL_UTILS     /* ExecuTorch Kernel Utils */
/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.5.1 */
#define RTE_ML_EXECUTORCH_RUNTIME     /* ExecuTorch Runtime */


#endif /* RTE_COMPONENTS_H */
