#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
"""Write the test image of the traffic counter as a C array: traffic/test_image.c.

    python traffic/make_test_image.py [<image file or URL>]

The image is letterboxed to the model input (model/traffic.py: IMAGE_SIZE, the
Ultralytics grey padding) and stored as interleaved RGB888, what the camera
path hands over. The default is image 257 of COCO train2017 (in COCO128), a
road with trucks. The photo is not ours to redistribute, so the generated file is not
committed (.gitignore); run this once before the first build.

It also prints what the float model finds in it, the reference for the board.
"""

from __future__ import annotations

import ssl
import sys
import urllib.request
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "model"))

DEFAULT = "http://images.cocodataset.org/train2017/000000000257.jpg"


def fetch(source: str) -> bytes:
    if "://" not in source:
        return Path(source).read_bytes()
    import certifi

    context = ssl.create_default_context(cafile=certifi.where())
    with urllib.request.urlopen(source, context=context) as response:
        return response.read()


def main() -> None:
    import cv2
    import torch

    from traffic import CLASS_NAMES, IMAGE_SIZE, YoloVehicles, decode, letterbox, load_detection_model, to_input

    source = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    bgr = cv2.imdecode(np.frombuffer(fetch(source), np.uint8), cv2.IMREAD_COLOR)
    rgb, _, _ = letterbox(bgr, IMAGE_SIZE)

    with torch.no_grad():
        box, score = YoloVehicles(load_detection_model()).eval()(to_input(rgb))
    detections = decode(box[0].numpy(), score[0].numpy(), 0.25)
    reference = [
        f"{CLASS_NAMES[int(d[5])]} x1 {d[0]:.0f} y1 {d[1]:.0f} x2 {d[2]:.0f} y2 {d[3]:.0f} score {d[4]:.2f}" for d in detections
    ]
    print("float model on the host:", *reference, sep="\n  ")

    data = rgb.tobytes()
    rows = [", ".join(f"0x{b:02x}" for b in data[i : i + 24]) for i in range(0, len(data), 24)]
    comment = "\n".join(f"//   {r}" for r in reference)
    (HERE / "test_image.c").write_text(
        "// Generated by traffic/make_test_image.py -- do not edit, do not commit.\n"
        f"// {source}, letterboxed to {IMAGE_SIZE} x {IMAGE_SIZE}, RGB888.\n"
        f"// The float model on the host finds (score > 0.25):\n{comment}\n"
        '#include "test_image.h"\n'
        f"__attribute__((aligned(16))) const unsigned char test_image[{len(data)}] = {{\n  "
        + ",\n  ".join(rows)
        + "\n};\n",
        newline="\n",
    )
    (HERE / "test_image.h").write_text(
        "// Generated by traffic/make_test_image.py -- do not edit, do not commit.\n"
        "#pragma once\n"
        f"#define TEST_IMAGE_SIZE {IMAGE_SIZE}\n"
        "#ifdef __cplusplus\n"
        'extern "C" {\n'
        "#endif\n"
        "extern const unsigned char test_image[];  // TEST_IMAGE_SIZE x TEST_IMAGE_SIZE x 3, RGB888\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n",
        newline="\n",
    )
    print(f"wrote {HERE / 'test_image.c'} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
