/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.15.1+p3-gf46d68bf
 *
 * Project: 'usb-hil.Release+NuMaker-X-M55M1D' 
 * Target:  'Release+NuMaker-X-M55M1D' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55M1.h"

/* Nuvoton::CMSIS Driver:USB Device:M55M1_M5531_HS@1.2.0 */
#define RTE_Driver_USBD
#define RTE_Driver_USBD1
#define RTE_USBD1 1
/* Nuvoton::Device:Common:M55M1_M5531@1.0.0 */
#define PRJ_RTE_DEVICE_HEADER   "RTE_Device.h"


#endif /* RTE_COMPONENTS_H */
