/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.15.1+p3-gf46d68bf
 *
 * Project: 'camera-hil.Release+NuMaker-X-M55M1D' 
 * Target:  'Release+NuMaker-X-M55M1D' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.26.5 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
