/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.15.1+p3-gf46d68bf
 *
 * Project: 'camera-hil.Release+NuMaker-X-M55M1D' 
 * Target:  'Release+NuMaker-X-M55M1D' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55M1.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.26.5 */
#define RTE_ETHOS_U_CORE_DRIVER
/* ARM::SDS:IO:Custom@3.0.0 */
#define RTE_SDS_IO                              /* SDSIO */
#define RTE_SDS_IO_CLIENT                       /* SDSIO-Client */
#define RTE_SDS_IO_CLIENT_CUSTOM                /* SDSIO-Client via Custom Interface */
/* ARM::SDS:Stream&CMSIS-RTOS2@3.1.0 */
#define RTE_SDS                                 /* Synchronous Data Stream (SDS) */
/* Keil::USB&MDK:CORE@8.0.2 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Device:Custom Class@8.0.2 */
#define RTE_USB_Device_CustomClass_0    /* USB Device Custom Class instance 0 */

/* Keil::USB&MDK:Device@8.0.2 */
#define RTE_USB_Device_0                /* USB Device 0 */

/* Nuvoton::Board Support:Camera:CMOS-720P&HM1055@1.2.0 */
#define RTE_NuMaker_CMOS_720P_HM1055
/* Nuvoton::Board Support:Display:NuMaker-TFT-LCD5&LT7381@1.1.0 */
#define RTE_NuMaker_TFT_LCD5_LT7381
/* Nuvoton::Board Support:Memory:HyperRAM&NuMaker-X-M55M1D@1.0.0 */
#define RTE_NuMaker_M55M1_HyperRAM
/* Nuvoton::CMSIS Driver:USB Device:M55M1_M5531_HS@1.1.0 */
#define RTE_Driver_USBD
#define RTE_Driver_USBD1
#define RTE_USBD1 1
/* Nuvoton::Device:Common:M55M1_M5531@1.0.0 */
#define PRJ_RTE_DEVICE_HEADER   "RTE_Device.h"


#endif /* RTE_COMPONENTS_H */
