// Generated by create_ai_layer.py -- do not edit.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
extern const unsigned char model_pte[];
extern const unsigned long model_pte_size;
#ifdef __cplusplus
}
#endif
