/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p88-g94cb0c5e
 *
 * Project: 'quake.Debug+SSE-320-U85' 
 * Target:  'Debug+SSE-320-U85' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U85@1.26.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u85


#endif /* PRE_INCLUDE_GLOBAL_H */
